[build]
publish = "exampleSite/public"

[build.environment]
NODE_VERSION = "17.6.0"
HUGO_VERSION = "0.93.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[context.production]
command = "cd exampleSite && npm install && hugo --minify --themesDir=../../ --theme=repo"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && npm install && hugo --minify --themesDir=../../ --theme=repo -b=$DEPLOY_PRIME_URL"
